# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170331_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('Below 18', 'Below 18'), ('18 to 25', '18 to 25'), ('26 to 35', '26 to 35'), ('Above 35', 'Above 35')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, null=True),
        ),
    ]
