# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='From')),
                ('end_date', models.DateField(null=True, verbose_name='Upto')),
                ('area', models.IntegerField(default=24000, verbose_name='Area in sq.km')),
                ('latitude_from', models.FloatField(blank=True, null=True)),
                ('latitude_to', models.FloatField(blank=True, null=True)),
                ('longitude_from', models.FloatField(blank=True, null=True)),
                ('longitude_to', models.FloatField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, choices=[('Coringa and Godaveri Estuary', 'Coringa and Godaveri Estuary'), ('Horsely Hills', 'Horsely Hills')], max_length=30, null=True, verbose_name='Site Name')),
                ('type_of_location', models.CharField(max_length=50, null=True)),
                ('terrain', models.CharField(blank=True, choices=[('WETLANDS', 'Wetlands'), ('GALLIFORM', 'Galliform'), ('HERONARY', 'Heronary'), ('TERRESTIAL', 'Terrestial')], max_length=15)),
                ('breeding_time', models.PositiveIntegerField(blank=True, verbose_name='Breeding Time(in weeks)')),
                ('block_count', models.IntegerField(verbose_name='Block Count')),
                ('forest_type', models.CharField(blank=True, choices=[('Tropical Wet Evergreen Forest', 'Tropical Wet Evergreen Forest'), ('Tropical Semi-Evergreen Forest', 'Tropical Semi-Evergreen Forest'), ('Tropical Moist Deciduous Forest', 'Tropical Moist Deciduous Forest'), ('Littoral and Swamp Forest', ' Littoral and Swamp Forest'), ('Tropical Dry Deciduous Forest', 'Tropical Dry Deciduous Forest')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Bird')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Iba',
            fields=[
                ('iba_id', models.AutoField(primary_key=True, serialize=False)),
                ('iba_code', models.CharField(max_length=10, null=True)),
                ('iba_name', models.CharField(max_length=200)),
                ('pa', models.CharField(max_length=20, null=True)),
                ('criteria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.CharField(max_length=10)),
                ('sci_name', models.CharField(max_length=100)),
                ('com_name', models.CharField(max_length=100)),
                ('b_family', models.CharField(max_length=200)),
                ('redlist', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(max_length=3, null=True)),
                ('state_name', models.CharField(max_length=50)),
                ('state_capital', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='district_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State'),
        ),
        migrations.AddField(
            model_name='bird',
            name='iba_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Iba', verbose_name='IBA Code'),
        ),
        migrations.AddField(
            model_name='bird',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Species'),
        ),
        migrations.AddField(
            model_name='bird',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State', verbose_name='State'),
        ),
    ]
