# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 3, 31, 21, 57, 18, 736430, tzinfo=utc), verbose_name='date published')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('iba_code', models.CharField(max_length=10)),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('protocol_type', models.CharField(max_length=50)),
                ('trip_comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bird',
            name='iba_code',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='species',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='state',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Observation'),
        ),
        migrations.DeleteModel(
            name='Bird',
        ),
    ]
