# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='site_name',
            field=models.CharField(blank=True, choices=[('Coringa and Godaveri Estuary', 'Coringa and Godaveri Estuary'), ('Horsely Hills', 'Horsely Hills')], max_length=30, null=True, verbose_name='Site Name'),
        ),
    ]
