# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170331_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='iba_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Iba'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 23, 20, 52, 308717, tzinfo=utc), verbose_name='date published'),
        ),
    ]
