# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170119_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Upto'),
        ),
        migrations.AddField(
            model_name='bird',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='From'),
        ),
    ]
