# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170331_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 23, 21, 54, 410457, tzinfo=utc), verbose_name='date published'),
        ),
    ]
