# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170331_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 4, 18, 14, 767251, tzinfo=utc), verbose_name='date published'),
        ),
    ]
