# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170331_2106'),
        ('data', '0005_auto_20170401_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 6, 0, 0, 331220, tzinfo=utc), verbose_name='date published'),
        ),
    ]
