# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170119_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Iba',
            fields=[
                ('iba_id', models.AutoField(primary_key=True, serialize=False)),
                ('iba_code', models.CharField(max_length=10, null=True)),
                ('iba_name', models.CharField(max_length=200)),
                ('pa', models.CharField(max_length=20, null=True)),
                ('criteria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(max_length=3, null=True)),
                ('state_name', models.CharField(max_length=50)),
                ('state_capital', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.District'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='iba_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Iba', verbose_name='IBA Code'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State'),
        ),
    ]
