# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170401_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 6, 2, 20, 908682, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
