# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_bird_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Upto'),
        ),
        migrations.AddField(
            model_name='bird',
            name='start_date',
            field=models.DateField(null=True, verbose_name='From'),
        ),
    ]
