# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20170401_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 12, 24, 37, 340135, tzinfo=utc), verbose_name='date published'),
        ),
    ]
