# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170401_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('spi_id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=30)),
                ('sciname', models.CharField(max_length=30)),
                ('roi_species', models.CharField(max_length=1400)),
                ('eip', models.CharField(max_length=800)),
                ('edc', models.CharField(max_length=160)),
                ('freq', models.CharField(max_length=160)),
                ('dprob', models.CharField(max_length=600)),
                ('dear', models.CharField(max_length=1)),
                ('cspec', models.CharField(max_length=685)),
                ('habitat', models.CharField(max_length=210)),
                ('migchange', models.CharField(max_length=380)),
                ('vagrancy', models.CharField(max_length=420)),
                ('spopspec', models.CharField(max_length=430)),
                ('poptrend', models.CharField(max_length=680)),
            ],
        ),
        migrations.CreateModel(
            name='visual_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 10, 23, 44, 507376, tzinfo=utc), verbose_name='date published'),
        ),
    ]
