# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_bird_type_of_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Bird')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
