# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.CharField(max_length=10)),
                ('sci_name', models.CharField(max_length=20)),
                ('com_name', models.CharField(max_length=20)),
                ('b_family', models.CharField(max_length=20)),
                ('redlist', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Species'),
        ),
    ]
