# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20170329_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='b_family',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='com_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='sci_name',
            field=models.CharField(max_length=100),
        ),
    ]
