# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Please enter a valid name')])),
                ('Paper_ID', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\\d{1,14}$')])),
                ('Amount', models.IntegerField()),
                ('Bank', models.CharField(max_length=50)),
                ('Reference_Number', models.IntegerField()),
                ('Date_of_Fee_Deposited', models.DateField()),
                ('Accommodation', models.BooleanField()),
                ('Food_Choice', models.CharField(choices=[('NONVEG', 'Non-Veg'), ('VEG', 'Veg')], max_length=10)),
            ],
        ),
    ]
