# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettable', '0002_auto_20170331_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='redlist',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
