# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assettable', '0003_redlist_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='area',
        ),
        migrations.RemoveField(
            model_name='state',
            name='forest_area',
        ),
    ]
