# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettable', '0004_auto_20170331_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iba',
            name='area',
            field=models.FloatField(null=True),
        ),
    ]
