# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettable', '0005_auto_20170401_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='spc',
            fields=[
                ('spc_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=50)),
                ('sci_name', models.CharField(max_length=50)),
                ('obs_count', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('obs_date', models.DateField()),
            ],
        ),
    ]
